/**
 * Downloads the site's webfonts from Google Fonts and rewrites the CSS to point at
 * local copies. Run once; the resulting files are committed.
 *
 * Why self-host: a farmer opening this page in Mauke on a metered 4G connection
 * should not also be making requests to a third party. Same-origin fonts mean the
 * page has exactly one host, no tracking, and no dependency on fonts.gstatic.com
 * being reachable.
 *
 *   bun site/tools/fetch-fonts.ts
 */

const FAMILIES = [
  "Fraunces:ital,opsz,wght@0,9..144,300..900",
  "Instrument+Sans:wght@400..700",
  "DM+Mono:wght@300;400;500",
];

// Google serves one @font-face per unicode subset. We only ship latin + latin-ext;
// the rest are dead weight for an English/Cook Islands Māori audience.
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const outDir = new URL("../assets/fonts/", import.meta.url).pathname;

let css = "";
for (const family of FAMILIES) {
  const res = await fetch(
    `https://fonts.googleapis.com/css2?family=${family}&display=swap`,
    { headers: { "User-Agent": UA } },
  );
  if (!res.ok) {
    console.error(`! ${family} → HTTP ${res.status}`);
    continue;
  }
  css += (await res.text()) + "\n";
}

// Blocks look like:  /* latin */\n@font-face { ... src: url(https://...woff2) ... }
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
console.log(`parsed ${blocks.length} @font-face blocks`);

const out: string[] = [
  "/* Self-hosted webfonts. Generated by site/tools/fetch-fonts.ts — do not hand-edit. */",
];
const seen = new Set<string>();

for (const [, subset, block] of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue;
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;

  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? "font";
  const weight = (block.match(/font-weight:\s*([^;]+);/)?.[1] ?? "400").trim().replace(/\s+/g, "-");
  const name = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${subset}.woff2`;

  if (!seen.has(name)) {
    const bin = await fetch(url, { headers: { "User-Agent": UA } });
    await Bun.write(outDir + name, await bin.arrayBuffer());
    seen.add(name);
    console.log(`  ↓ ${name}`);
  }
  out.push(block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(./${name})`));
}

await Bun.write(outDir + "fonts.css", out.join("\n\n") + "\n");
console.log(`\nwrote ${seen.size} font files + fonts.css`);
